site_name: jQuery Technical Report
nav:
  - Índice: index.md
  - Introdução: introduction.md
  - Características: features.md
  - Utilização: usage.md
  - Tópicos Avançados: advanced.md
  - Referências: references.md

theme:
  name: 'swan'
  highlightjs: true